In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
municipios = pd.read_csv("municipios.csv")

In [3]:
municipios.head()

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
0,5200050,Abadia de Goiás,-16.75730,-49.4412,0,52,1050,62,America/Sao_Paulo
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31,4001,34,America/Sao_Paulo
2,5200100,Abadiânia,-16.19700,-48.7057,0,52,9201,62,America/Sao_Paulo
3,3100203,Abaeté,-19.15510,-45.4444,0,31,4003,37,America/Sao_Paulo
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15,401,91,America/Sao_Paulo

In [13]:
municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   codigo_ibge   5570 non-null   int64
 1   nome          5570 non-null   object
 2   latitude      5570 non-null   float64
 3   longitude     5570 non-null   float64
 4   capital       5570 non-null   int64
 5   codigo_uf     5570 non-null   int64
 6   siafi_id      5570 non-null   int64
 7   ddd           5570 non-null   int64
 8   fuso_horario  5570 non-null   object
dtypes: float64(2), int64(5), object(2)
memory usage: 391.8+ KB

In [14]:
municipios.query("codigo_uf==13")

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
170,1300029,Alvarães,-3.22727,-64.8007,0,13,289,97,America/Porto_Velho
195,1300060,Amaturá,-3.37455,-68.2005,0,13,291,97,America/Porto_Velho
216,1300086,Anamã,-3.56697,-61.3963,0,13,293,97,America/Porto_Velho
252,1300102,Anori,-3.74603,-61.6575,0,13,203,97,America/Porto_Velho
286,1300144,Apuí,-7.19409,-59.8960,0,13,969,97,America/Porto_Velho
...,...,...,...,...,...,...,...,...,...
5188,1304203,Tefé,-3.36822,-64.7193,0,13,281,97,America/Porto_Velho
5259,1304237,Tonantins,-2.86582,-67.7919,0,13,9851,97,America/Porto_Velho
5345,1304260,Uarini,-2.99609,-65.1133,0,13,9849,97,America/Porto_Velho
5400,1304302,Urucará,-2.52936,-57.7538,0,13,285,92,America/Porto_Velho
5404,1304401,Urucurituba,-3.12841,-58.1496,0,13,287,92,America/Porto_Velho

In [15]:
municipios.query("capital==1")

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
294,2800308,Aracaju,-10.909100,-37.0677,1,28,3105,79,America/Sao_Paulo
580,1501402,Belém,-1.455400,-48.4898,1,15,427,91,America/Sao_Paulo
592,3106200,Belo Horizonte,-19.910200,-43.9266,1,31,4123,31,America/Sao_Paulo
642,1400100,Boa Vista,2.823840,-60.6753,1,14,301,95,America/Porto_Velho
755,5300108,Brasília,-15.779500,-47.9297,1,53,9701,61,America/Sao_Paulo
972,5002704,Campo Grande,-20.448600,-54.6295,1,50,9051,67,America/Porto_Velho
1491,5103403,Cuiabá,-15.601000,-56.0974,1,51,9067,65,America/Porto_Velho
1508,4106902,Curitiba,-25.419500,-49.2646,1,41,7535,41,America/Sao_Paulo
1812,4205407,Florianópolis,-27.594500,-48.5477,1,42,8105,48,America/Sao_Paulo
1831,2304400,Fortaleza,-3.716640,-38.5423,1,23,1389,85,America/Sao_Paulo
1927,5208707,Goiânia,-16.686400,-49.2643,1,52,9373,62,America/Sao_Paulo
2595,2507507,João Pessoa,-7.115090,-34.8641,1,25,2051,83,America/Sao_Paulo
2831,1600303,Macapá,0.034934,-51.0694,1,16,605,96,America/Sao_Paulo
2839,2704302,Maceió,-9.665990,-35.7350,1,27,2785,82,America/Sao_Paulo
2885,1302603,Manaus,-3.118660,-60.0212,1,13,255,92,America/Porto_Velho
3239,2408102,Natal,-5.793570,-35.1986,1,24,1761,84,America/Sao_Paulo
3531,1721000,Palmas,-10.240000,-48.3558,1,17,9733,63,America/Sao_Paulo
3947,4314902,Porto Alegre,-30.031800,-51.2065,1,43,8801,51,America/Sao_Paulo
3977,1100205,Porto Velho,-8.760770,-63.8999,1,11,3,69,America/Porto_Velho
4110,2611606,Recife,-8.046660,-34.8771,1,26,2531,81,America/Sao_Paulo
4193,1200401,Rio Branco,-9.974990,-67.8243,1,12,139,68,America/Rio_Branco
4207,3304557,Rio de Janeiro,-22.912900,-43.2003,1,33,6001,21,America/Sao_Paulo
4332,2927408,Salvador,-12.971800,-38.5011,1,29,3849,71,America/Sao_Paulo
4810,2111300,São Luís,-2.538740,-44.2825,1,21,921,98,America/Sao_Paulo
4853,3550308,São Paulo,-23.532900,-46.6395,1,35,7107,11,America/Sao_Paulo
5209,2211001,Teresina,-5.091940,-42.8034,1,22,1219,86,America/Sao_Paulo
5533,3205309,Vitória,-20.315500,-40.3128,1,32,5705,27,America/Sao_Paulo

In [16]:
cap = municipios.query("capital==1")
cap

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
294,2800308,Aracaju,-10.909100,-37.0677,1,28,3105,79,America/Sao_Paulo
580,1501402,Belém,-1.455400,-48.4898,1,15,427,91,America/Sao_Paulo
592,3106200,Belo Horizonte,-19.910200,-43.9266,1,31,4123,31,America/Sao_Paulo
642,1400100,Boa Vista,2.823840,-60.6753,1,14,301,95,America/Porto_Velho
755,5300108,Brasília,-15.779500,-47.9297,1,53,9701,61,America/Sao_Paulo
972,5002704,Campo Grande,-20.448600,-54.6295,1,50,9051,67,America/Porto_Velho
1491,5103403,Cuiabá,-15.601000,-56.0974,1,51,9067,65,America/Porto_Velho
1508,4106902,Curitiba,-25.419500,-49.2646,1,41,7535,41,America/Sao_Paulo
1812,4205407,Florianópolis,-27.594500,-48.5477,1,42,8105,48,America/Sao_Paulo
1831,2304400,Fortaleza,-3.716640,-38.5423,1,23,1389,85,America/Sao_Paulo
1927,5208707,Goiânia,-16.686400,-49.2643,1,52,9373,62,America/Sao_Paulo
2595,2507507,João Pessoa,-7.115090,-34.8641,1,25,2051,83,America/Sao_Paulo
2831,1600303,Macapá,0.034934,-51.0694,1,16,605,96,America/Sao_Paulo
2839,2704302,Maceió,-9.665990,-35.7350,1,27,2785,82,America/Sao_Paulo
2885,1302603,Manaus,-3.118660,-60.0212,1,13,255,92,America/Porto_Velho
3239,2408102,Natal,-5.793570,-35.1986,1,24,1761,84,America/Sao_Paulo
3531,1721000,Palmas,-10.240000,-48.3558,1,17,9733,63,America/Sao_Paulo
3947,4314902,Porto Alegre,-30.031800,-51.2065,1,43,8801,51,America/Sao_Paulo
3977,1100205,Porto Velho,-8.760770,-63.8999,1,11,3,69,America/Porto_Velho
4110,2611606,Recife,-8.046660,-34.8771,1,26,2531,81,America/Sao_Paulo
4193,1200401,Rio Branco,-9.974990,-67.8243,1,12,139,68,America/Rio_Branco
4207,3304557,Rio de Janeiro,-22.912900,-43.2003,1,33,6001,21,America/Sao_Paulo
4332,2927408,Salvador,-12.971800,-38.5011,1,29,3849,71,America/Sao_Paulo
4810,2111300,São Luís,-2.538740,-44.2825,1,21,921,98,America/Sao_Paulo
4853,3550308,São Paulo,-23.532900,-46.6395,1,35,7107,11,America/Sao_Paulo
5209,2211001,Teresina,-5.091940,-42.8034,1,22,1219,86,America/Sao_Paulo
5533,3205309,Vitória,-20.315500,-40.3128,1,32,5705,27,America/Sao_Paulo

In [6]:
estados = pd.read_csv("estados.csv")


estados.head()

   COD                NOME SIGLA
0   35           São Paulo    SP
1   41              Paraná    PR
2   42      Santa Catarina    SC
3   43   Rio Grande do Sul    RS
4   50  Mato Grosso do Sul    MS